### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by munkh-erdene** [yt7589/iching#1]
Hi,
Please can you add your data?

FileNotFoundError: [Errno 2] File ./data/tp/sh601006_trend.csv does not exist: './data/tp/sh601006_trend.csv'

**Comment by yt7589** [comment]
Hi.
Thanks for your interest in this project. Because the dataset is big I had ignore it in this repository. Would you like to give me your email I will send the dataset to you? By the way this project is still at its very early stage, I am working on this project now. You may find many feature is missing now. Please be patient.

**Comment by munkh-erdene** [comment]
Ok thanks.
Plesae send it to me 

odforme@gmail.com.

**Comment by yt7589** [comment]
I had sent the dataset and checkpoints folder zip files to your email. If you have any question please contact me. You are welcome.
